version: '3.4'
services:
  ngrok:
    image: wernight/ngrok
    # links:
    #   - web
    ports: 
      - "4040:4040"
    volumes: 
      - .:/home/ngrok/.ngrok2/
    depends_on: 
      - web
    environment:
      - DOMAIN=web
      - PORT=80
    command:
    - /bin/sh
    - -c
    - |
      ngrok http 40

  web:
    build: ./app/.
    links: 
      - mongodb
      # - redis
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "5000:5000"
    container_name: counterapp02
    networks:
      - mongodb

  # redis:
  #   image: "redis"
  #   build:
  #     context: .
  #     dockerfile: ./redis/Dockerfile
  #   command: redis-server --bind 0.0.0.0  --maxmemory 256mb --maxmemory-policy allkeys-lru --appendonly yes
  #   ports:
  #     - "6379:3000"
  #   restart: always
  #   volumes:
  #     - ./redis.conf:/usr/local/etc/redis/redis.conf
  #     - ./data/redis:/data
  #   container_name: redis_container
  #   networks:
  #     - redis

  mongodb:
    image: "mongodb"
    build:
      context: .
      dockerfile: ./mongo/Dockerfile
    restart: always
    # environment:
    #   Mongo_USER: ${DB_USER}
    #   Mongo_PASSWORD: ${DB_PASS}
    #   Mongo_DATABASE: ${DB_COLLECTION}
    container_name: monogodb_container
    networks: 
      - mongodb
  
  cvapp: 
    build: ./cv
    links: 
      - web
    networks:
      - mongodb

networks:
  mongodb:
    driver: bridge
    
  
    